### ISSUE TITLE
The currency field is required

### ISSUE THREAD

**Issue by liamka** [inxy-payments/merchant-sdk#6]
Your api updated, but php package is not

**PLS UPDATE PHP PACKAGE**

**Comment by apvalkov** [comment]
@liamka which version of the package you are using?

**Comment by liamka** [comment]
Latest

**Comment by apvalkov** [comment]
@liamka Please check again that you are using version 3.1.3 and package method 
`$merchantSDK->createSession($sessionRequest);`

For this method, we removed the required currency and set it based on the currency selected in your profile.

**Comment by DmitriyNovok** [comment]
I have the same problem. package version 3.1.3. method `$merchantSDK->createSession($sessionRequest)` throws an exception Client error: POST https://sandbox.api.inxy.io/api/v1/sessions resulted in a 422 Unprocessable Content response: {"message":"The currency field is required.","errors":{"currency":["The currency field is required."]}}

**Comment by liamka** [comment]
Resolved
